spring:
  application:
    name: authentication
server:
  port: ${PORT:0}
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST_SERVER}:${EUREKA_SERVER_PORT}/eureka
  server:
    enableSelfPreservation: 'false'
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
oauth:
  client:
    secret: ${AUTHENTICATION_PASS}
    name: ${AUTHENTICATION_USER}
authorization:
  jwt:
    secret: ${AUTHORIZATION_JWT_SECRET}
logging:
  level:
    org:
      springframework:
        security: DEBUG
