spring:
  application:
    name: authentication
server:
  port: ${PORT:0}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT}/eureka
  server:
    enableSelfPreservation: 'false'
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
oauth:
  client:
    secret: myappsecret123
    name: myappname123
jwt:
  secret: MY-JWT-SECRET

