version: '3.5'
services:
  app:
    tty: true
    container_name: app
    build:
      context: .
    ports:
      - "8282:80"
    #restart: always
    environment:
      APP_VERSION: 1.0.0
      APP_ENVIRONMENT: 'docker-compose'
    
      