openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'BAG API'
  description: API for the brazona administration games application, which provides information for connecting to the app api interface. 

paths:
  /authentication/oauth2/token:

    post:
      summary: Fetch the authentication token
      responses:
        '200':
          description: This endpoint provides the application access token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'
        404:
          description: No Auth found for the provided `UserId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    UserId:
      description: The unique identifier of a Auth
      type: string
    Auth:
      type: object
      required:
        - username
        - password
        - grand_type
      properties:
        id:
          $ref: '#/components/schemas/UserId'
        name:
          type: string
        type:
          type: string
          enum:
            - capsule
            - probe
            - satellite
            - spaceplane
            - station
        description:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    BasicAuth:
      type: BasicAuth
      in: header
      name: X-Basic-Auth
security:
  - BasicAuth: []