swagger: '2.0'
info:
  version: '1.0.0'
  title: 'BAG API '
  description: Brazona Administration Games

consumes:
  - application/json
produces:
  - application/json

paths:
definitions:
  Error:
    type: object
    required:
      - message
    properties:
      message:
        description: A human readable error message
        type: string
