name: Deploy Application in Kube
on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      image_docker:
        required: true
        type: string
      dns:
        required: true
        type: string
      namespace:
        required: true
        type: string
jobs:
  deploy:
    name: Deploy Kubernetes
    runs-on: ubuntu-latest
    permissions: write-all
    environment:
      name: ${{inputs.env_name}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Deploy to Cluster
        run: | 
          manifest=`cat "./app-ui/deployment.yaml" | sed 's/$NAMESPACE/${{ inputs.NAMESPACE }}/ ; s/$DNS/${{ inputs.DNS }}/ ; s/$TAG/${{inputs.image_docker}}/ ; s/$APP_VERSION/${{inputs.image_docker}}/ ; s/$APP_ENVIRONMENT/${{inputs.env_name}}/' ./app-ui/deployment.yaml`
          echo "$manifest" | kubectl apply -f -