spring:
  application:
    name: api-gateway
server:
  port: ${API_GATEWAY_PORT}
zuul:
  routes:
    authentication:
      path: /authentication/**
      service-id: authentication
      sensitive-headers: Cookie,Set-Cookie
    users:
      path: /users/**
      service-id: users
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST_SERVER}:${EUREKA_SERVER_PORT}/eureka
  server:
    enableSelfPreservation: 'false'
ribbon:
  ReadTimeout: '20000'
  ConnectTimeout: '10000'
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: '60000'

authorization:
  jwt:
    secret: ${AUTHORIZATION_JWT_SECRET}
oauth:
  client:
    secret: ${AUTHENTICATION_PASS}
    name: ${AUTHENTICATION_USER}

logging:
  level:
    org:
      springframework:
        security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  swagger-ui:
    csrf:
      enabled: true