name: Build Docker Image
on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      build_number_org:
        required: true
        type: string
      image_name:
        required: true
        type: string
      path_dockerfile:
        required: true
        type: string
env:
  REGISTRY: ghcr.io
jobs:
  build:
    name: Build and Push Docker image 
    runs-on: ubuntu-latest
    permissions: write-all
    environment:
      name: ${{ inputs.env_name }}
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Docker Build and Push Image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        env:
          MICROSERVICES_NAME: ${{ inputs.image_name}}
        with:
          context: ${{ inputs.path_dockerfile}}
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.MICROSERVICES_NAME }}:${{ inputs.build_number_org }}

      