name: Run Delete Branch Feature/Release 
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: ${{ inputs.branch }} 
