name: Run Merge Branch and Delete Feature/Release
on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
env:
  BRANCH_TARGET: ${{ github.base_ref }}
  BRANCH_SOURCE: ${{ github.head_ref }}
jobs:
  merge:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
      - name: BRANCH_TARGET
        run: echo "${{ env.BRANCH_TARGET }}" 
      - name: BRANCH_SOURCE
        run: echo "${{ env.BRANCH_SOURCE }}"
      - name: Merge ${{env.BRANCH_SOURCE}} -> ${{env.BRANCH_SOURCE}}
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{env.BRANCH_SOURCE}}
          target_branch: ${{env.BRANCH_SOURCE}}
          github_token: ${{ secrets.GITHUB_TOKEN }}