name: Run Merge Branch and Delete Feature/Release
on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
env:
  BRANCH_TARGET: ${{ github.ref_name }}
  BRANCH_SOURCE: ${{ github.ref_name }} 
  EVENT_TYPE: ${{ github.event_name }} 
jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
      - name: BRANCH_TARGET
        run: echo "${{ env.BRANCH_TARGET }}" 
      - name: BRANCH_SOURCE
        run: echo "${{ env.BRANCH_SOURCE }}" 
      - name: EVENT_TYPE
        run: echo "${{ env.EVENT_TYPE }}"